name: test

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: test

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: config
      id: config
      run: |
        echo "REPO=ghcr.io/gertd/sver-test" >> $GITHUB_ENV

    - name: sver-cur
      uses: ./.github/actions/sver-cur
      id: "sver-cur"
      with:
        docker_image: "gertd/sver-test"
        docker_registry: "ghcr.io"
        docker_username: "gertd"
        docker_password: ${{ secrets.GITHUB_TOKEN }}

    - name: sver-new
      uses: ./.github/actions/sver-new
      id: "sver-new"
      with:
        docker_image: "gertd/sver-test"
        docker_registry: "ghcr.io"
        docker_username: "gertd"
        docker_password: ${{ secrets.GITHUB_TOKEN }}

    - name: calc-tags-cur
      id: "tags-cur"
      run: |
        echo "version: ${{ steps.sver-cur.outputs.version }}"

        while read -r tag; do
          tags="$tags ${{ env.REPO }}:$tag"
        done < <(echo "${{ steps.sver-cur.outputs.version }}")
        echo ::set-output name=tags::$tags

    - name: calc-tags-new
      id: "tags-new"
      run: |
        echo "version: ${{ steps.calc-tags-new.outputs.version }}"

        while read -r tag; do
          tags="$tags ${{ env.REPO }}:$tag"
        done < <(echo "${{ steps.sver-new.outputs.version }}")

        echo "tags<<EOF" >> $GITHUB_OUTPUT
        echo "$tags" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: show-tags-cur
      id: "show-tags-cur"
      run: |
        echo "tags-cur: ${{ steps.tags-cur.outputs.tags }}"

    - name: show-tags-new
      id: "show-tags-new"
      run: |
        echo "tags-new: ${{ steps.tags-new.outputs.tags }}"
